name: Kubernetes Container Actions
description: ''
enabled: true
queryString: |-
  flb.source=docker
  | Action=*
  | regex("^(?<action>[^:\s]+)(:\s(?<parameter>.+))?",field=Action)
  | groupBy([action],function=[])
backfillLimit: 0
schedule: '*/5 * * * *'
queryEnd: now
$schema: https://schemas.humio.com/scheduledsearch/v0.1.0
timeZone: UTC+00:00
queryStart: 30d
actionNameReferences:
- Kubernetes Container Actions Lookup
