name: Kubernetes Cluster Hostnames
description: collect kubernetes hostnames for lookup
enabled: true
queryString: |-
  hostname=*
  | groupBy(field=hostname,function=[])
backfillLimit: 0
schedule: '*/5 * * * *'
queryEnd: now
$schema: https://schemas.humio.com/scheduledsearch/v0.1.0
timeZone: UTC+00:00
queryStart: 4h
actionNameReferences:
- Kubernetes Cluster Hostnames Lookup
