name: Installed Application Events - Find SSL Versions
visualization:
  options: {}
  type: table-view
$schema: https://schemas.humio.com/query/v0.1.0
timeInterval:
  isLive: false
  start: 7d
queryString: |-
  // Installed Application Events - Find SSL Versions

  // Find anything where OpenSSL is installed. Requires Discover or Spotlight.
  #event_simpleName=InstalledApplication openssl

  // Create a formatted list.
  | opensslDetails:=format("%-38s\n\t└ %s", field=[AppSource, AppName])

  // Add the ComputerName.
  | $"crowdstrike/fltr-core:zComputerName"()

  // Group by aid and collect the string from above.
  | groupBy([aid, ComputerName], function=collect(opensslDetails, limit=1000), limit=max)
